apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-infra
  namespace: argocd
spec:
  description: projects for cluster infrastructure
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    -  https://github.com/rasenmic/gitops-trial
  sourceNamespaces:
    - argocd
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'