apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: cluster-infra
  source:
    repoURL: https://github.com/rasenmic/gitops-trial
    path: argocd/cluster-infra/misc/
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
